FROM node

# Create app directory
WORKDIR /usr/app

# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
# where available (npm@5+)
COPY package*.json ./

RUN npm install
# If you are building your code for production
# RUN npm install --only=production
RUN npx prisma init
RUN npx tsc --init

# Bundle app source
COPY . .

# for typescript
RUN npm run build
COPY nodemon.json ./dist/
COPY .env ./dist/
COPY prisma/schema.prisma ./dist/prisma/
WORKDIR ./dist

EXPOSE 5000
CMD node src/server.js