### Get All Getails
GET http://127.0.0.1:5000/student/ HTTP/1.1

### Add Student
POST http://127.0.0.1:5000/student/ HTTP/1.1
Content-Type: application/json

{
    "id":2,
    "studentName":"Prasad",
}
